server:
  port: 8000
  servlet:
    context-path: /
    session:
      cookie:
        name: ueboot-shiro
spring:
  cache:
    type: redis
    cache-names: systemCache
  session:
    store-type: redis
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  jpa:
    open-in-view: true
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
        format_sql: false
      jadira:
        usertype:
          autoRegisterUserTypes: true
          javaZone: Asia/Shanghai
          databaseZone: Asia/Shanghai
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    # 本地开发需要自己配置对应的数据库
    url: jdbc:mysql://127.0.0.1:3306/ueboot-shiro?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    tomcat:
      max-wait: 500
      max-active: 200
      initial-size: 5
      max-idle: 5
      min-idle: 5
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    database: 1
    timeout: 60s
  data:
    redis:
      repositories:
        enabled: false #设置为false,防止启动时提示Multiple Spring Data modules found, entering strict repository configuration mode
logging:
  level:
    root: info
    # 设置显示sql参数值
#    org.hibernate: info
#    org.hibernate.type.descriptor.sql.BasicBinder: trace
#    org.hibernate.type.descriptor.sql.BasicExtractor: trace
