server:
  port: 8000
  session:
    cookie: ueboot-shiro
  servlet:
    context-path: /
spring:
  cache:
    type: redis
    cache-names: systemCache
  session:
    store-type: Redis
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  jpa:
    open-in-view: true
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
        format_sql: false
      jadira:
        usertype:
          autoRegisterUserTypes: true
          javaZone: Asia/Shanghai
          databaseZone: Asia/Shanghai
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    # 本地开发需要自己配置对应的数据库
    url: jdbc:mysql://120.26.102.228:3306/acmplatform?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: accp
    tomcat:
      max-wait: 500
      max-active: 200
      initial-size: 5
      max-idle: 5
      min-idle: 5
  redis:
    host: 127.0.0.1
    password: 1234567890
    port: 6379
    database: 1
    timeout: 60000
    jedis:
      pool:
        max-active: 20
        max-wait: 1000
        max-idle: 100
        min-idle: 5
logging:
  level:
    root: info
    # 设置显示sql参数值
#    org.hibernate: info
#    org.hibernate.type.descriptor.sql.BasicBinder: trace
#    org.hibernate.type.descriptor.sql.BasicExtractor: trace
